// <auto-generated />
using System;
using EF_core_empty_controler__Day_3_.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_core_empty_controler__Day_3_.Migrations
{
    [DbContext(typeof(bookauthorContext))]
    partial class bookauthorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_core_empty_controler__Day_3_.Models.Author", b =>
                {
                    b.Property<int>("authid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("authid"));

                    b.Property<string>("authname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("authid");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            authid = 11,
                            authname = "Prathamesh"
                        },
                        new
                        {
                            authid = 12,
                            authname = "Anna"
                        },
                        new
                        {
                            authid = 13,
                            authname = "shetty"
                        });
                });

            modelBuilder.Entity("EF_core_empty_controler__Day_3_.Models.Book", b =>
                {
                    b.Property<int>("bookid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bookid"));

                    b.Property<DateOnly>("Publicationyear")
                        .HasColumnType("date");

                    b.Property<int>("authid")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bookid");

                    b.HasIndex("authid");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            bookid = 1,
                            Publicationyear = new DateOnly(2025, 5, 6),
                            authid = 11,
                            price = 999m,
                            title = "swarg"
                        },
                        new
                        {
                            bookid = 2,
                            Publicationyear = new DateOnly(2020, 4, 4),
                            authid = 12,
                            price = 500m,
                            title = "shap"
                        },
                        new
                        {
                            bookid = 3,
                            Publicationyear = new DateOnly(2020, 5, 7),
                            authid = 13,
                            price = 150m,
                            title = "jhatu"
                        });
                });

            modelBuilder.Entity("EF_core_empty_controler__Day_3_.Models.Book", b =>
                {
                    b.HasOne("EF_core_empty_controler__Day_3_.Models.Author", "author")
                        .WithMany("Books")
                        .HasForeignKey("authid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("author");
                });

            modelBuilder.Entity("EF_core_empty_controler__Day_3_.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
